# Generated by Django 6.1 on 2026-08-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="dish",
        ),
        migrations.AddField(
            model_name="order",
            name="dishes",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="catalog.dish"
            ),
        ),
    ]
