# Generated by Django 6.1 on 2026-09-01 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_order_dishes_order_dish_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["dish_name"]},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["username"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="order",
            name="dish",
        ),
        migrations.AddField(
            model_name="order",
            name="dishes",
            field=models.ManyToManyField(related_name="orders", to="catalog.dish"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="cooked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.position"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_taker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
